### ISSUE TITLE
Открытие ссылок соцсетей в новых вкладках

### ISSUE THREAD

**Issue by AntonZelinsky** [Studio-Yandex-Practicum/lubimovka_frontend#552]
На странице авторов (например https://stage.dev.lubimovka.ru/nikon_veselova) есть ссылки на социальные сети и при нажатии на их, открытие происходит не в новом окне, а в текущем, несмотря на то, что переход на внешний сайт. Нужно сделать открытие в новом окне для этого блока

**Comment by MADeit0** [comment]
PR #553
