### ISSUE TITLE
На странице проекта вместо строки "О проекте" печатать строку, выдаваемую API

### ISSUE THREAD

**Issue by FinemechanicPub** [Studio-Yandex-Practicum/lubimovka_frontend#559]
![изображение](https://github.com/user-attachments/assets/f48eb770-9687-4bdd-a6df-d25c3537e784)

На страницах проектов (https://lubimovka.art/projects/{id}) над блоком описания проекта нужно выводить строчку из поля "description_caption" (получается из запроса API api/v1/projects/{id}/).

https://lubimovka.art/api/v1/projects/8/
![image](https://github.com/user-attachments/assets/91795344-a7fe-4951-a52e-a7e6221d3d4d)

**Comment by MADeit0** [comment]
с сервера сейчас приходят данные без этого поля, мне нечем заменить поле
<img width="668" alt="Снимок экрана 2024-09-06 в 21 34 40" src="https://github.com/user-attachments/assets/d4e663c1-2e53-4fba-add9-622413fa7159">

**Comment by FinemechanicPub** [comment]
> с сервера сейчас приходят данные без этого поля, мне нечем заменить поле <img alt="Снимок экрана 2024-09-06 в 21 34 40" width="668" src="https://private-user-images.githubusercontent.com/111721183/365271770-d4e663c1-2e53-4fba-add9-622413fa7159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDk5MTAsIm5iZiI6MTcyNTY0OTYxMCwicGF0aCI6Ii8xMTE3MjExODMvMzY1MjcxNzcwLWQ0ZTY2M2MxLTJlNTMtNGZiYS1hZGQ5LTYyMjQxM2ZhNzE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxOTA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzgzYmJjODZlNzcwYTA1NWIyZjY2NmNkMjhmYWJmZjg5YzRmZmM2MzgwMGRkMTViYWYzNDYwZTJlMmE0OWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8i0FIqG6GkYVPYIoce1w5gS-ahLqcmnP16u5J7g8Fgk">

С сервера приходит вот что:
https://stage.dev.lubimovka.ru/api/v1/projects/4/

У тебя на скриншоте уже что-то обработанное в js. Может быть нужно обновить код клиентов, как написано вот [здесь https://github.com/Studio-Yandex-Practicum/](lubimovka_frontend#%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B0%D0%B9%D0%BF%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2-api)

**Comment by MADeit0** [comment]
да я понял похоже, запрос же выполняется на сервере, а не на клиенте, поэтому в тулзе я не увижу ответ от запроса
