### ISSUE TITLE
Проблема с отображением ссылок на спектакли

### ISSUE THREAD

**Issue by AntonZelinsky** [Studio-Yandex-Practicum/lubimovka_frontend#567]
Тип события `Спектакль` в Афише отличается от других типов. Когда создаётся это событие, генерируется отдельная страница для каждого спектакля. Вот пример такого спектакля https://lubimovka.art/performances/10
Когда в афише находится спектакль, на него должна добавляться прямая ссылка. Такое поведение было раньше, но сейчас почему-то не работает. 
В этом [PR](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/377/files) была реализована эта логика. 

Необходимо разобраться почему сейчас в афише не отображается ссылка на спектакль и исправить эту проблему.

Страница афиши на проде и ссылка на апи:
https://lubimovka.art/schedule
https://lubimovka.art/api/v1/schema/swagger-ui/#/afisha/afisha_events_list

Как фронт должен определять спктакль ли это и откуда брать его id? из свойства performance_id, которое приходит в афише. Если там есть идентификатор, то значит нужно отображать ссылку на спектакль, если там null, то не отображать.

**Comment by FinemechanicPub** [comment]
Вот более поздний PR на эту тему:
https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/497

**Comment by MADeit0** [comment]
#569
