### ISSUE TITLE
Линии разной толщины

### ISSUE THREAD

**Issue by AntonZelinsky** [Studio-Yandex-Practicum/lubimovka_frontend#573]
Вторая линия должна быть такой же, как первая — тонкой.
![image](https://github.com/user-attachments/assets/ef2e6e8f-2bc8-4aa3-b3ee-53c15f29d4ab)

**Comment by VLGrigoryan** [comment]
<img width="348" alt="Screenshot 2024-09-06 at 17 29 40" src="https://github.com/user-attachments/assets/34c50462-9554-4a43-9a25-09e08d8cf483">
<img width="416" alt="Screenshot 2024-09-06 at 17 29 48" src="https://github.com/user-attachments/assets/c56df6a7-c2a3-4cf7-9fa9-1e4e999a996c">

обе линии одинаковой ширины

**Comment by AntonZelinsky** [comment]
А посмотри на проде https://lubimovka.art/
Может фикс был, но ещё не доехал до прода, но там проблема всё ещё есть. Думаю, проблема в том, что там две линии и одна сдвинута на пиксель
![image](https://github.com/user-attachments/assets/867410a3-6870-4722-a0df-9afda151f877)

**Comment by AntonZelinsky** [comment]
Как я вижу, проблема не устранена @VLGrigoryan

**Comment by VLGrigoryan** [comment]
@AntonZelinsky у меня обе линии одинаковы
<img width="1440" alt="Screenshot 2024-09-13 at 21 29 02" src="https://github.com/user-attachments/assets/ea89a8da-9449-4128-9ab1-8ac6e79ab953">
<img width="1440" alt="Screenshot 2024-09-13 at 21 29 05" src="https://github.com/user-attachments/assets/2d047e2f-be82-42d8-bf59-37cc92d9fa09">
<img width="1440" alt="Screenshot 2024-09-13 at 21 36 03" src="https://github.com/user-attachments/assets/2daa1b1c-412b-40f8-b8e6-4d8eca8fe26d">
не могу найти ошибку

**Comment by FinemechanicPub** [comment]
> не могу найти ошибку

Возможная причина - в том, что установленный впроекте пакет [postcss-pxtorem](https://www.npmjs.com/package/postcss-pxtorem) преобразует в стилях толщину в пикселах в относительные единицы **rem**. При отрисовке страницы из-за ошибок округления линия отображается то толстой, то тонкой в зависимости от размеров окна.

Возможные решения:

- изменить параметр **width** стиля `.actions-slot` с 1px на 0.5px, тогда postcss-pxtorem не будет преобразовывать это значение, а браузер округлит до целого пиксела;
- изменить параметр **width** стиля `.actions-slot` с 1px на 1PX, тогда postcss-pxtorem не будет преобразовывать это значение ([документация](https://www.npmjs.com/package/postcss-pxtorem#a-message-about-ignoring-properties));
- изменить параметр **minPixelValue** в настроечном файле [postcss.config.js](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/postcss.config.js) на, например 2, тогда параметр толщины линии перестанет пробразовываться, но возможно побочные эффекты, связанные с другими элементами толщиной 1px;

**Comment by FinemechanicPub** [comment]
Более тщательное обследование выявило, что предложенные в предыдущем комментарии меры не устраняют проблему полностью.

Другой вариант решения - изменить подход к выводу вертикальной черты. Вместо элемента заданной толщины для отрисовки линии использовать стилевой параметр border-right.

Применение следующих параметров к первому и второму блоку навигации даёт удовлетворительный визуальный результат:

```css
border-right: 1px solid black;
margin-top: 3px;
```
![image](https://github.com/user-attachments/assets/906a1ae2-0614-43b7-a92b-88b5aa2ba642)

При этом существующий стиль для элемента ::after удалить
```css
  &:not(:last-child)::after {
    position: absolute;
    right: 0;
    bottom: 0;
    display: block;
    width: 1px;
    height: 80%;
    background-color: var(--coal);
    content: "";
  }
```
