### ISSUE TITLE
Добавить часовой пояс к событиям в афише

### ISSUE THREAD

**Issue by AntonZelinsky** [Studio-Yandex-Practicum/lubimovka_frontend#580]
В афише добавить московский часовой пояс (мск) сразу после времени.
Чтобы было что-то типа такого:
![image](https://github.com/user-attachments/assets/cc2e6b9c-81c2-4a1b-914d-b86971b6a1f0)

такими же буквачками как месяц перед временем.

Обратить внимание, что события афиши выводятся на странице афиши, на главной и в блоках конструктора. Везде должно выводиться мск

**Comment by MADeit0** [comment]
не совсем понимаю как можно открыть конструктор на сайте?
